### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rvanasa** [dfinity/feedback#1]
Feel free to add / modify items or link individual issues as needed.

Repository:
- [x] Set up live reloading via [`mo-dev`](https://www.npmjs.com/package/mo-dev)
- [x] Set up Motoko unit testing
- [x] Add documentation for setting up local environment
- [x] Prompt to install recommended VS Code extensions
- [x] Set up test runner CI

Backend:
- [x] Create a feedback item registry with basic ownership
- [x] Implement voting and changing status
- [x] Explore ways of verifying Auth0 social login using HTTP outcalls
- [x] Refactor to use a more general `User` representation
- [x] Refactor `fetch()` to return `TopicView[]` with computed fields such as `votes`, `yourVote`, `owned`, etc.

Frontend:
- [x] Create a basic UI layout for viewing feedback items
- [x] Include a simple request submission form
- [x] Add a custom favicon
- [x] Set up Internet Identity authentication
- [x] Explore different options for social login (Google, GitHub, Discord, Twitter, developer forum, etc.)
- [x] Support basic Markdown in feedback descriptions
- [x] Add mobile support
- [x] Include stylized tooltips
- [x] Set up optimistic rendering (client-side simulation of canister behavior)
- [x] Include filters for open, active, completed, and closed requests

Next steps:
- [x] NFID authentication
- [x] Bulk import from Jira
- [x] Custom rendering for GitHub and Jira links
- [x] URLs for individual topics
- [x] Recovery logs
- [x] Topic moderation
- [x] #50
- [x] Ability to search, filter, and sort topics

Post-launch features:
- [x] #108 
- [x] Tag autofill and interactions
- [ ] #49
- [ ] Ability to merge topics
- [ ] Extended moderation (topic edit queue, comments, etc.)
- [ ] User profile customization
- [ ] Paginated search results
- [ ] Team-specific pages

Integrations:
- [ ] Auth0 token verification using HTTP outcalls
- [ ] Developer forum integration
- [ ] OpenChat integration
